// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqgvpcdvojufmwfwqlbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZ3ZwY2R2b2p1Zm13ZndxbGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTI4NTUsImV4cCI6MjA2NDA4ODg1NX0.m8D4pur5eWwZawD_MjY4xrQTC-w5wyhWr8e2v2rsXR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);